import { IQuoteRequest } from '@/interfaces/quote.interface';
import { IUser } from '@/interfaces/user.interface';

export const INITIAL_DEMO_USERS: IUser[] = [
  {
    id: 'user-admin-1',
    name: 'Marcus Vance',
    email: 'marcus.vance@apexcad.com',
    company: 'ApexCAD Construction & Engineering',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'user-client-1',
    name: 'Jane Doe',
    email: 'jane.doe@horizondevelopments.com',
    company: 'Horizon Developments Ltd.',
    role: 'client',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_DEMO_QUOTES: IQuoteRequest[] = [
  {
    id: 'q-101',
    clientName: 'Jane Doe',
    clientEmail: 'jane.doe@horizondevelopments.com',
    clientPhone: '+1 (555) 234-5678',
    companyName: 'Horizon Developments Ltd.',
    projectName: 'Horizon Plaza Tower - Structural Design',
    projectType: 'commercial',
    squareFootage: 48500,
    location: 'Austin, TX',
    targetBudget: 3500000,
    desiredTimeline: '14 Months',
    description: 'Require detailed structural engineering quote and foundation load-bearing validation for a 12-story commercial office tower with subterranean parking.',
    status: 'in_review',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    designFiles: [
      {
        filename: 'Horizon_Tower_Structural_Layout.pdf',
        handle: '5aYkEQJSQCmYShsoCnZN', // Demo Filestack handle
        url: 'https://cdn.filestackcontent.com/5aYkEQJSQCmYShsoCnZN',
        mimetype: 'application/pdf',
        size: 4820000,
        uploadDate: new Date(Date.now() - 86400000 * 2).toISOString(),
      },
      {
        filename: 'Subterranean_Foundation_CAD.dwg',
        handle: 'zLpQxWk9S4mVRJ4A7u2b',
        url: 'https://cdn.filestackcontent.com/zLpQxWk9S4mVRJ4A7u2b',
        mimetype: 'image/png',
        size: 8900000,
        uploadDate: new Date(Date.now() - 86400000 * 2).toISOString(),
      },
    ],
    adminNotes: 'Initial load calculations reviewed by Lead Structural Engineer. Drafting preliminary estimate.',
  },
  {
    id: 'q-102',
    clientName: 'Robert Sterling',
    clientEmail: 'r.sterling@sterlingestates.com',
    clientPhone: '+1 (555) 987-6543',
    companyName: 'Sterling Luxury Estates',
    projectName: 'Oakwood Hillside Contemporary Villa',
    projectType: 'residential',
    squareFootage: 7200,
    location: 'Aspen, CO',
    targetBudget: 1200000,
    desiredTimeline: '8 Months',
    description: 'Custom luxury hillside residence with cantilevered steel frame decks, floor-to-ceiling glass facades, and geothermal HVAC integration.',
    status: 'quote_sent',
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    designFiles: [
      {
        filename: 'Oakwood_Villa_Architectural_Elevation.pdf',
        handle: '5aYkEQJSQCmYShsoCnZN',
        url: 'https://cdn.filestackcontent.com/5aYkEQJSQCmYShsoCnZN',
        mimetype: 'application/pdf',
        size: 3400000,
        uploadDate: new Date(Date.now() - 86400000 * 5).toISOString(),
      },
    ],
    response: {
      estimatedCost: 1285000,
      estimatedTimelineWeeks: 34,
      architectNotes: 'Estimate includes specialized high-altitude foundation anchors and heavy timber structural framing.',
      costBreakdown: [
        { id: 'b1', category: 'Architectural & Engineering Review', description: 'Stamp drawings & MEP signoff', amount: 45000 },
        { id: 'b2', category: 'Site Excavation & Foundation', description: 'Hillside rock anchor foundation', amount: 320000 },
        { id: 'b3', category: 'Structural Steel & Glass Frame', description: 'Custom cantilever steel superstructure', amount: 540000 },
        { id: 'b4', category: 'MEP & Finish Contracting', description: 'Geothermal HVAC & luxury interior prep', amount: 380000 },
      ],
      respondedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
      respondedBy: 'Marcus Vance',
    },
  },
  {
    id: 'q-103',
    clientName: 'Elena Rostova',
    clientEmail: 'elena@apexlogistics.io',
    companyName: 'Apex Logistics Corp',
    projectName: 'Bayside Automated Distribution Hub',
    projectType: 'industrial',
    squareFootage: 120000,
    location: 'Savannah, GA',
    targetBudget: 8500000,
    desiredTimeline: '18 Months',
    description: 'High-bay automated distribution center with 40ft clear height, heavy duty slab for AGVs, and 24 loading docks.',
    status: 'pending',
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    designFiles: [
      {
        filename: 'Bayside_Site_Plan_DXF.dxf',
        handle: 'zLpQxWk9S4mVRJ4A7u2b',
        url: 'https://cdn.filestackcontent.com/zLpQxWk9S4mVRJ4A7u2b',
        mimetype: 'application/pdf',
        size: 12500000,
        uploadDate: new Date(Date.now() - 86400000 * 1).toISOString(),
      },
    ],
  },
];
